import { useState } from 'react';
import { useRouter } from 'expo-router';
import { Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import Check from '../assets/figma/check.svg';
import Chevron from '../assets/figma/chevron.svg';
import { PageHeader, PrimaryButton, Screen, SetupProgress, textStyles } from '../src/components/UI';
import { cultureFromLanguage, foodCultures } from '../src/data/personalization';
import { useProfile } from '../src/store/ProfileContext';
import { colors as c } from '../src/theme';

export default function Culture() {
  const router = useRouter();
  const { culture, setCulture } = useProfile();
  const [choosing, setChoosing] = useState(false);
  const selected = foodCultures.find(item => item.value === culture) ?? foodCultures[0];
  const suggested = Platform.OS === 'web' && typeof navigator !== 'undefined' ? cultureFromLanguage(navigator.language) : null;
  return <Screen contentStyle={s.root}><View><PageHeader title="Set up" onBack={() => router.back()} /><SetupProgress step={1} /><Text style={[textStyles.heading, s.title]}>{'What food feels familiar\nto you?'}</Text><Text style={[textStyles.body, s.description]}>We’ll use one familiar food culture as the reference point for comparisons.</Text><Text style={s.note}>Choose from the participating countries.</Text><View style={s.selected}><View style={s.mark}><Text style={s.markText}>{selected.code}</Text></View><View style={s.selectedCopy}><Text style={s.cultureName}>{selected.label}</Text><Text style={s.suggestion}>{selected.country} · {suggested === culture ? 'Suggested from language' : 'Selected by you'}</Text></View><View style={s.selectedCheck}><Check width={18} height={18} /></View></View><Pressable accessibilityRole="button" accessibilityState={{ expanded: choosing }} onPress={() => setChoosing(!choosing)} style={s.change}><Text style={s.changeText}>Choose another culture</Text><Chevron width={18} height={18} /></Pressable>{choosing && <View style={s.cultureList}>{foodCultures.map(option => <Pressable accessibilityRole="button" accessibilityState={{ selected: culture === option.value }} key={option.value} onPress={() => { setCulture(option.value); setChoosing(false); }} style={s.cultureOption}><View><Text style={s.changeText}>{option.label}</Text><Text style={s.country}>{option.country}</Text></View>{culture === option.value && <Check width={16} height={16} />}</Pressable>)}</View>}</View><View style={s.action}><PrimaryButton title="Continue" onPress={() => router.push('/preference')} /></View></Screen>;
}
const s = StyleSheet.create({ root: { justifyContent: 'space-between' }, title: { marginBottom: 18 }, description: { marginBottom: 8 }, note: { color: c.muted, fontSize: 12, marginBottom: 18 }, selected: { minHeight: 94, borderRadius: 24, backgroundColor: c.lavender, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16 }, mark: { width: 52, height: 52, borderRadius: 18, backgroundColor: c.white, alignItems: 'center', justifyContent: 'center', marginRight: 14 }, markText: { color: c.blue, fontSize: 13, fontWeight: '700' }, selectedCopy: { flex: 1, gap: 4 }, cultureName: { fontSize: 17, lineHeight: 22, fontWeight: '600', color: c.ink }, suggestion: { fontSize: 12, color: c.muted }, selectedCheck: { width: 34, height: 34, borderRadius: 17, backgroundColor: c.lime, justifyContent: 'center', alignItems: 'center' }, change: { minHeight: 48, borderRadius: 16, borderWidth: 1, borderColor: c.line, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 18 }, changeText: { color: c.ink, fontSize: 14, fontWeight: '500' }, cultureList: { backgroundColor: c.white, borderWidth: 1, borderColor: c.line, borderRadius: 16, marginTop: 6, overflow: 'hidden' }, cultureOption: { paddingHorizontal: 16, minHeight: 58, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: c.line }, country: { color: c.muted, fontSize: 11, marginTop: 2 }, action: { paddingTop: 18 } });
