import { useRouter } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import CameraBlue from '../assets/figma/camera-blue.svg';
import Gallery from '../assets/figma/gallery.svg';
import Chevron from '../assets/figma/chevron.svg';
import { PrimaryButton, Screen } from '../src/components/UI';
import { colors as c } from '../src/theme';
import { useMenuImageInput } from '../src/components/MenuImageInput';
import { useProfile } from '../src/store/ProfileContext';

export default function Home() {
  const router = useRouter();
  const { savedScans } = useProfile();
  const picker = useMenuImageInput(() => router.push({ pathname: '/scanner', params: { mode: 'photo' } }));
  const recent = savedScans[0];
  return <Screen nav="home" scroll>{picker.inputs}<Text style={s.greeting}>Good afternoon</Text><Text style={s.title}>{'What are we trying\ntoday?'}</Text><View style={s.hero}><View style={s.heroTop}><View style={s.heroCopy}><Text style={s.label}>SCAN A MENU</Text><Text style={s.heroTitle}>Point. Scan. Understand.</Text><Text style={s.heroDescription}>Get a familiar explanation in seconds.</Text></View><View style={s.orb}><CameraBlue width={34} height={34} /></View></View><PrimaryButton title="Scan a menu" onPress={() => router.push('/scanner')} /><Pressable onPress={picker.openUpload} style={s.upload}><Gallery width={18} height={18} /><Text style={s.uploadText}>Upload a photo instead</Text></Pressable></View>{picker.error && <Text style={{ color: '#B85037', fontSize: 12, marginBottom: 14 }}>{picker.error}</Text>}<View style={s.recentHeader}><Text style={s.recentTitle}>Recent scan</Text><Pressable onPress={() => router.push('/saved')}><Text style={s.seeAll}>See all</Text></Pressable></View><Pressable onPress={() => router.push(recent ? '/saved' : '/scanner')} style={s.recentCard}><View style={s.country}><Text style={s.countryText}>{recent ? '✓' : '5'}</Text></View><View style={s.recentCopy}><Text style={s.recentName}>{recent ? recent.place : 'Ready for your first menu'}</Text><Text style={s.recentMeta}>{recent ? recent.date : 'Prototype supports 5 selected dishes'}</Text></View><Chevron width={18} height={18} /></Pressable></Screen>;
}
const s = StyleSheet.create({ greeting: { color: c.muted, fontSize: 13, lineHeight: 17, marginBottom: 6 }, title: { color: c.ink, fontSize: 27, lineHeight: 31, fontWeight: '600', marginBottom: 32 }, hero: { height: 344, backgroundColor: c.lavender, borderRadius: 28, paddingHorizontal: 20, paddingTop: 22, paddingBottom: 20, marginBottom: 18 }, heroTop: { flex: 1, flexDirection: 'row', justifyContent: 'space-between' }, heroCopy: { width: '62%' }, label: { color: c.blue, fontSize: 11, fontWeight: '600', marginBottom: 7 }, heroTitle: { color: c.ink, fontSize: 22, lineHeight: 26, fontWeight: '600', marginBottom: 7 }, heroDescription: { color: c.muted, fontSize: 12, lineHeight: 17 }, orb: { width: 98, height: 98, borderRadius: 32, borderWidth: 1, borderColor: c.line, backgroundColor: c.white, alignItems: 'center', justifyContent: 'center' }, upload: { height: 48, backgroundColor: c.white, borderRadius: 16, marginTop: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9 }, uploadText: { fontSize: 13, color: c.ink, fontWeight: '500' }, recentHeader: { height: 24, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 18 }, recentTitle: { fontSize: 15, color: c.ink, fontWeight: '600' }, seeAll: { fontSize: 12, color: c.blue, fontWeight: '500' }, recentCard: { height: 86, borderRadius: 20, backgroundColor: c.light, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14 }, country: { width: 48, height: 48, borderRadius: 16, backgroundColor: c.paleLime, justifyContent: 'center', alignItems: 'center', marginRight: 12 }, countryText: { color: c.ink, fontSize: 11, fontWeight: '700' }, recentCopy: { flex: 1, gap: 4 }, recentName: { color: c.ink, fontSize: 14, fontWeight: '600' }, recentMeta: { color: c.muted, fontSize: 11 } });
