import { useRouter } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import Check from '../assets/figma/check.svg';
import LearnDot from '../assets/figma/learn-dot.svg';
import { PageHeader, PreferenceCard, PrimaryButton, Screen, SetupProgress, textStyles } from '../src/components/UI';
import { useProfile } from '../src/store/ProfileContext';
import { colors as c } from '../src/theme';

export default function Preference() {
  const router = useRouter();
  const { avoidsOrganMeat, setAvoidsOrganMeat, completeOnboarding } = useProfile();
  return <Screen contentStyle={s.root}><View><PageHeader title="Set up" onBack={() => router.back()} /><SetupProgress step={2} /><Text style={[textStyles.heading, s.title]}>One quick preference</Text><Text style={[textStyles.body, s.description]}>We’ll learn the rest gradually, so you don’t have to fill out a long profile.</Text><PreferenceCard><Text style={s.question}>How do you feel about organ meat?</Text><Text style={s.explain}>This preference is saved for future dishes and profile updates.</Text><Pressable accessibilityRole="radio" accessibilityState={{ selected: avoidsOrganMeat }} onPress={() => setAvoidsOrganMeat(true)} style={[s.option, avoidsOrganMeat && s.optionSelected]}>{avoidsOrganMeat && <View style={s.check}><Check width={15} height={15} /></View>}<Text style={[s.optionText, avoidsOrganMeat && { color: c.white }]}>I’d rather avoid it</Text></Pressable><Pressable accessibilityRole="radio" accessibilityState={{ selected: !avoidsOrganMeat }} onPress={() => setAvoidsOrganMeat(false)} style={[s.option, !avoidsOrganMeat && s.optionSelected, { marginTop: 14 }]}>{!avoidsOrganMeat && <View style={s.check}><Check width={15} height={15} /></View>}<Text style={[s.optionText, !avoidsOrganMeat && { color: c.white }]}>I’m okay with it</Text></Pressable></PreferenceCard><View style={s.learn}><LearnDot width={12} height={12} /><Text style={s.learnText}>Your profile improves as you scan more food.</Text></View></View><View><PrimaryButton title="Save & continue" onPress={() => { completeOnboarding(); router.replace('/home'); }} /><Pressable onPress={() => { completeOnboarding(); router.replace('/home'); }} style={s.skip}><Text style={s.skipText}>Skip for now</Text></Pressable></View></Screen>;
}
const s = StyleSheet.create({ root: { justifyContent: 'space-between' }, title: { marginBottom: 18 }, description: { marginBottom: 18 }, question: { color: c.ink, fontSize: 20, lineHeight: 25, fontWeight: '600', marginBottom: 14 }, explain: { color: c.muted, fontSize: 13, lineHeight: 18, marginBottom: 14 }, option: { height: 58, borderWidth: 1, borderColor: c.line, borderRadius: 18, backgroundColor: c.white, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 10 }, optionSelected: { borderColor: c.blue, backgroundColor: c.blue }, optionText: { color: c.ink, fontSize: 15, fontWeight: '600' }, check: { width: 28, height: 28, borderRadius: 14, backgroundColor: c.white, justifyContent: 'center', alignItems: 'center' }, learn: { height: 58, borderRadius: 18, backgroundColor: c.paleLime, marginTop: 18, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, gap: 12 }, learnText: { color: c.ink, fontSize: 12, fontWeight: '500' }, skip: { height: 36, justifyContent: 'flex-end' }, skipText: { color: c.muted, fontSize: 13, fontWeight: '500' } });
