import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import Sliders from '../assets/figma/sliders.svg';
import Chevron from '../assets/figma/chevron.svg';
import Sparkle from '../assets/figma/sparkle-profile.svg';
import { Screen, TagChip } from '../src/components/UI';
import { useProfile } from '../src/store/ProfileContext';
import { colors as c } from '../src/theme';

const cultures = ['Korean', 'Japanese', 'American', 'Chinese', 'French', 'Hungarian'];
const likeOptions = ['Fried food', 'Cheese', 'Beef', 'Crispy', 'Spicy'];
export default function TasteProfile() {
  const { profile, culture, setCulture, avoidsOrganMeat, setAvoidsOrganMeat, toggleLike, toggleAvoid } = useProfile();
  const [editingCulture, setEditingCulture] = useState(false);
  const [editingAvoid, setEditingAvoid] = useState(false);
  return <Screen nav="profile" scroll><View style={s.header}><Text style={s.title}>Taste profile</Text><Pressable accessibilityRole="button" accessibilityLabel="Edit taste preferences" onPress={() => setEditingAvoid(!editingAvoid)}><Sliders width={21} height={21} /></Pressable></View><Text style={s.subtitle}>{'Built gradually from what you tell us and what you\nchoose.'}</Text><Pressable accessibilityRole="button" onPress={() => setEditingCulture(!editingCulture)} style={s.culture}><View><Text style={s.cultureLabel}>Familiar food culture</Text><Text style={s.cultureValue}>{culture}</Text></View><Chevron width={18} height={18} /></Pressable>{editingCulture && <View style={s.editPanel}>{cultures.map(item => <Pressable accessibilityRole="button" key={item} onPress={() => { setCulture(item); setEditingCulture(false); }} style={s.editChoice}><Text style={s.editText}>{item}</Text></Pressable>)}</View>}<View style={s.likes}><Text style={s.sectionLabel}>LIKES · TAP TO CHANGE</Text><View style={s.chips}>{likeOptions.slice(0, 3).map(item => <Pressable accessibilityRole="button" accessibilityState={{ selected: profile.likes.includes(item) }} key={item} onPress={() => toggleLike(item)}><TagChip title={item} lime={profile.likes.includes(item)} /></Pressable>)}</View><View style={s.chips}>{likeOptions.slice(3).map(item => <Pressable accessibilityRole="button" accessibilityState={{ selected: profile.likes.includes(item) }} key={item} onPress={() => toggleLike(item)}><TagChip title={item} blue={profile.likes.includes(item)} /></Pressable>)}</View></View><View style={s.avoids}><Text style={s.avoidLabel}>AVOIDS</Text><View style={s.chips}>{profile.avoids.map(item => <TagChip key={item} title={item} />)}</View></View>{editingAvoid && <View style={s.editPanel}><Text style={s.editHeading}>Ingredients to avoid</Text><Pressable accessibilityRole="button" onPress={() => setAvoidsOrganMeat(!avoidsOrganMeat)} style={s.editChoice}><Text style={s.editText}>{avoidsOrganMeat ? '✓ ' : ''}Organ meat</Text></Pressable><Pressable accessibilityRole="button" onPress={() => toggleAvoid('Strong fish smell')} style={s.editChoice}><Text style={s.editText}>{profile.avoids.includes('Strong fish smell') ? '✓ ' : ''}Strong fish smell</Text></Pressable></View>}<View style={s.learn}><Sparkle width={22} height={22} /><Text style={s.learnText}>Next scans can ask one small question when useful.</Text></View></Screen>;
}
const s = StyleSheet.create({ header: { height: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, title: { color: c.ink, fontSize: 26, lineHeight: 34, fontWeight: '600' }, subtitle: { color: c.muted, fontSize: 13, lineHeight: 18, marginTop: 14, marginBottom: 14 }, culture: { height: 86, borderRadius: 22, backgroundColor: c.lavender, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 }, cultureLabel: { color: c.muted, fontSize: 11, fontWeight: '500', marginBottom: 4 }, cultureValue: { color: c.ink, fontSize: 17, fontWeight: '600' }, likes: { height: 156, borderRadius: 22, backgroundColor: c.light, padding: 16, gap: 12, marginBottom: 14 }, sectionLabel: { color: c.muted, fontSize: 11, fontWeight: '600' }, chips: { flexDirection: 'row', gap: 8 }, avoids: { height: 122, borderRadius: 22, backgroundColor: '#FFF3E8', padding: 16, gap: 10, marginBottom: 14 }, avoidLabel: { color: '#F28A3A', fontSize: 11, fontWeight: '600' }, learn: { height: 68, borderRadius: 20, backgroundColor: c.paleLime, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 12 }, learnText: { color: c.ink, fontSize: 12, lineHeight: 15, fontWeight: '500', flex: 1 }, editPanel: { borderRadius: 18, borderWidth: 1, borderColor: c.line, marginBottom: 14, overflow: 'hidden' }, editChoice: { height: 40, paddingHorizontal: 16, justifyContent: 'center' }, editText: { color: c.ink, fontSize: 13 }, editHeading: { color: c.ink, fontSize: 13, fontWeight: '600', padding: 12 } });
